os: linux
dist: bionic

language: node_js
node_js:
  - lts/*
addons:
  ssh_known_hosts:
    - 206.189.63.151

cache:
  directories: 
  - node_modules # Cache node modules for faster installing

install:
  - npm install         # Install all npm modules
  - sudo apt-get install jq  # Command cli for reading json, needed to check package.json version

jobs:
  include:
    - stage: "Static Analysis"
      name: "Lint"
      script: npm run eslint
    - script: npm audit
      name: "Audit"
    - stage: "Test"
      script: npm run test
    - stage: "Build"
      script: npm run build --prod
    - stage: "Check tag and version"
      script: if [[ $TRAVIS_TAG =~ $( cat ./package.json | jq '.version' | cut -d'"' -f2 )$ ]]; then exit 0; else exit 1; fi
      install: skip
    - stage: "Deploy Development"
      script:
      - npm run build --prod
      - bash scripts/deploy_dev.sh
    - stage: "Deploy Beta"
      script:
      - npm run build --prod
      - bash scripts/deploy_beta.sh
    - stage: "Deploy Release"
      script:
      - npm run build --prod
      - bash scripts/deploy_release.sh
  allow_failures:


stages:
  - "Static Analysis"
  - "Test"
  - "Build"
  - name: "Deploy Development"
    if: NOT tag IS present AND type = push AND fork = false AND branch = develop
  - name: "Deploy Beta"
    if: NOT tag IS present AND type = push AND fork = false AND branch = master
  - name: "Check tag and version"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
  - name: "Deploy Release"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
