language: node_js
node_js:
  - lts/*
addons:
  ssh_known_hosts:
    - 206.189.63.151

install:
  - npm install         # Install all npm modules
  - sudo apt-get install jq  # Command cli for reading json, needed to check package.json version

jobs:
  include:
    - stage: "Static Analysis"
      name: "Lint"
      script: npm run eslint
    - script: npm audit
      name: "Audit"
    - stage: "Test"
      script: npm run test
    - stage: "Build"
      script: npm run build --prod
    - stage: "Check tag and version"
      script: cat ./package.json | jq '.version'
    - stage: "Deploy"
      script: bash _scripts/ci-test.sh

stages:
  - "Static Analysis"
  - "Test"
  - "Build"
  - name: "Check tag and version"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
  - name: "Deploy"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/