language: node_js
node_js:
- lts/*
addons:
  hosts:
  - http://206.189.63.151/
before_install:
- openssl aes-256-cbc -K $encrypted_e9ce4c9f2f9f_key -iv $encrypted_e9ce4c9f2f9f_iv
  -in deploy-key.enc -out deploy-key -d
