os: linux
dist: bionic

language: node_js
node_js:
  - lts/*
addons:
  ssh_known_hosts:
    - 206.189.63.151

cache:
  directories: 
  - node_modules # Cache node modules for faster installing

install:
  - yarn install         # Install all npm modules
  - sudo apt-get install jq  # Command cli for reading json, needed to check package.json version

jobs:
  include:
    - stage: "Static Analysis"
      name: "Lint"
      script: yarn eslint
    - script: yarn audit
      name: "Audit"
    - stage: "Test"
      script: yarn test
    - stage: "Build"
      script: yarn build --prod
    - stage: "Compare version and tag"
      script: if [[ $TRAVIS_TAG =~ $( cat ./package.json | jq '.version' | cut -d'"' -f2 )$ ]]; then exit 0; else exit 1; fi
      install: skip    
    - stage: "Deploy Development"
      script:
      - yarn doc        
      - yarn build --prod
      - bash scripts/deploy_dev.sh
    - stage: "Deploy Beta"
      script:
      - yarn doc
      - yarn build --prod
      - bash scripts/deploy_beta.sh
    - stage: "Deploy Release"
      script:
      - yarn doc
      - yarn build --prod
      - bash scripts/deploy_release.sh

stages:
  - "Static Analysis"
  - "Test"
  - "Build"
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-alpha(.\d+)*$/
  - name: "Deploy Development"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-alpha(.\d+)*$/
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-beta(.\d+)*$/
  - name: "Deploy Beta"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+-beta(.\d+)*$/
  - name: "Compare version and tag"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
  - name: "Deploy Release"
    if: tag IS present AND tag ~= /^v\d+.\d+.\d+$/
