language: node_js
node_js:
  - lts/*
addons:
  ssh_known_hosts:
    - 206.189.63.151

branches:
  only:
    - master
    - testing

after_success:
  - bash _scripts/ci-build.sh
  #- bash _scripts/ci-dep.sh


jobs:
  include:
    - stage: "Test"
      script: npm run test
    - script: npm run build --prod
    - stage: "Deploy"
      script: bash _scripts/ci-build.sh