name: Audit

on: push

jobs:
  linter:
    name: Audit libraries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Auditing
        run: yarn audit