name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - develop
      - master

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Linting
        run: yarn eslint
  audit:
    name: Audit libraries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Auditing
        run: yarn audit
  test:
    name: Test code
    runs-on: ubuntu-latest
    needs: [lint, audit]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Testing
        run: yarn test