name: Test

on: push

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    needs: [linter, audit]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Testing
        run: yarn test